# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
use_frameworks!
target 'Atem2' do

  # Pods for Atem2
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON', '~> 4.0'
end

